name: htrc-fall2019-workshops
channels:
  - conda-forge
  - htrc
dependencies:
  - python==3.7
  - numpy
  - matplotlib
  - pandas
  - geopy
  - nltk
  - scikit-learn
  - htrc-feature-reader
  - cartopy